# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: render-Rmd
on:
  schedule:
    - cron: '0 9-15 * * *'
  push:
    paths: ['**.Rmd']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ${{ github.workflow }}]')"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install curl package
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
          
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore(packages = "renv")'

      - name: Render index.Rmd
        run: |
          Rscript -e 'Sys.setenv(TZ="America/Los_Angeles"); rmarkdown::render("Index.Rmd")'

      - name: Commit changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "∆'s from github.workflow ${{ github.workflow }} [skip ${{ github.workflow }}]" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          